CREATE TABLE `trajetoria_candidatura` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(160) NOT NULL,
	`email` varchar(320) NOT NULL,
	`whatsapp` varchar(40) NOT NULL,
	`linkedin` varchar(320),
	`areaAtual` varchar(120) NOT NULL,
	`formacao` varchar(160) NOT NULL,
	`porque` text NOT NULL,
	`funcaoInteresse` varchar(120) NOT NULL,
	`jaEstudou` text NOT NULL,
	`maiorDificuldade` text NOT NULL,
	`horasSemana` varchar(40) NOT NULL,
	`expectativa` text NOT NULL,
	`disponibilidade` varchar(60) NOT NULL,
	`dispostoProjeto` boolean NOT NULL DEFAULT false,
	`porqueAgora` text NOT NULL,
	`bolsa` boolean NOT NULL DEFAULT false,
	`bolsaContexto` text,
	`consent` boolean NOT NULL DEFAULT false,
	`status` enum('new','interview','approved','waitlist','archived') NOT NULL DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `trajetoria_candidatura_id` PRIMARY KEY(`id`)
);
